version: "3"

services:
  redis:
    build: .
    ports:
      - "6379:6379"
    volumes:
      - data:/data
  vulncenter:
    image: vulncenter:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  data:
